name: YoJob
description: Where is my job?!
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  get: ^4.6.5
  rxdart: ^0.27.7
  cupertino_icons: ^1.0.2
  solid_lints: ^0.0.14
  crypto: ^3.0.2
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  google_sign_in: ^6.1.3
  google_fonts: ^4.0.4
  flutter_svg: ^0.23.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/google_logo.svg
    - lib/assets/email_icon.svg
    - lib/assets/key_icon.svg
    - lib/assets/building_icon.svg
    - lib/assets/employees_icon.svg
    - lib/assets/link_icon.svg
    - lib/assets/pencil_icon.svg
    - lib/assets/company_icon.svg
