// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9FJrkFt2D-j4mIPdeQ6sHzxsyB0nmVeI',
    appId: '1:420391593153:web:031b6bfd380135f958a040',
    messagingSenderId: '420391593153',
    projectId: 'yojob-3516a',
    authDomain: 'yojob-3516a.firebaseapp.com',
    storageBucket: 'yojob-3516a.appspot.com',
    measurementId: 'G-SDZ6TS2L24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUbFKiFRXYRQ32Aqx96mSgoGdaP4cVgJc',
    appId: '1:420391593153:android:ccd3b76ed43114e558a040',
    messagingSenderId: '420391593153',
    projectId: 'yojob-3516a',
    storageBucket: 'yojob-3516a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRT9dQkFCH30VtBxdwKFtm3BbfoNnuLDA',
    appId: '1:420391593153:ios:24096d97a271a44758a040',
    messagingSenderId: '420391593153',
    projectId: 'yojob-3516a',
    storageBucket: 'yojob-3516a.appspot.com',
    iosClientId: '420391593153-kh61qppes9lmmhkalk8u661fvlo6qdi9.apps.googleusercontent.com',
    iosBundleId: 'com.yojob.yojobflu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRT9dQkFCH30VtBxdwKFtm3BbfoNnuLDA',
    appId: '1:420391593153:ios:24096d97a271a44758a040',
    messagingSenderId: '420391593153',
    projectId: 'yojob-3516a',
    storageBucket: 'yojob-3516a.appspot.com',
    iosClientId: '420391593153-kh61qppes9lmmhkalk8u661fvlo6qdi9.apps.googleusercontent.com',
    iosBundleId: 'com.yojob.yojobflu',
  );
}
